blank_issues_enabled: false
contact_links:
  - name: ğŸ“š FAQs | å¸¸è§é—®é¢˜
    url: https://github.com/hiyouga/LLaMA-Factory/issues/4614
    about: Reading in advance is recommended | å»ºè®®æå‰é˜…è¯»
  - name: Discussions | è®¨è®ºåŒº
    url: https://github.com/hiyouga/LLaMA-Factory/discussions
    about: Please ask fine-tuning questions here | è¯·åœ¨è¿™é‡Œè®¨è®ºè®­ç»ƒé—®é¢˜
