name: test_new
channels:
  - huggingface
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - beautifulsoup4=4.12.3=pyha770c72_0
  - bzip2=1.0.8=hd590300_5
  - ca-certificates=2024.2.2=hbcca054_0
  - ld_impl_linux-64=2.40=h41732ed_0
  - libffi=3.4.2=h7f98852_5
  - libgcc-ng=13.2.0=h807b86a_5
  - libgomp=13.2.0=h807b86a_5
  - libnsl=2.0.1=hd590300_0
  - libsqlite=3.45.2=h2797004_0
  - libuuid=2.38.1=h0b41bf4_0
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.2.13=hd590300_5
  - ncurses=6.4.20240210=h59595ed_0
  - openssl=3.2.1=hd590300_1
  - pip=24.0=pyhd8ed1ab_0
  - python=3.10.14=hd12c33a_0_cpython
  - readline=8.2=h8228510_1
  - setuptools=69.2.0=pyhd8ed1ab_0
  - soupsieve=2.5=pyhd8ed1ab_1
  - tk=8.6.13=noxft_h4845f30_101
  - wheel=0.43.0=pyhd8ed1ab_1
  - xz=5.2.6=h166bdaf_0
  - pip:
      - accelerate==0.29.0
      - aenum==3.1.15
      - aiofiles==23.2.1
      - aiohttp==3.9.3
      - aiosignal==1.3.1
      - altair==5.3.0
      - annotated-types==0.6.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.3.0
      - appdirs==1.4.4
      - async-timeout==4.0.3
      - attrs==23.2.0
      - bitsandbytes==0.43.0
      - blendmodes==2024.1.1
      - certifi==2024.2.2
      - charset-normalizer==3.3.2
      - clean-fid==0.1.35
      - click==8.1.7
      - clip==1.0
      - contourpy==1.2.1
      - cycler==0.12.1
      - datasets==2.18.0
      - deepspeed==0.14.0
      - dill==0.3.8
      - diskcache==5.6.3
      - docker-pycreds==0.4.0
      - docstring-parser==0.16
      - einops==0.7.0
      - exceptiongroup==1.2.0
      - facexlib==0.3.0
      - fastapi==0.110.1
      - ffmpy==0.3.2
      - filelock==3.13.3
      - filterpy==1.4.5
      - fire==0.5.0
      - flash-attn==2.5.6
      - fonttools==4.51.0
      - frozenlist==1.4.1
      - fsspec==2024.2.0
      - ftfy==6.2.0
      - galore-torch==1.0
      - gitdb==4.0.11
      - gitpython==3.1.43
      - gradio==4.21.0
      - gradio-client==0.12.0
      - h11==0.14.0
      - hjson==3.1.0
      - httpcore==1.0.5
      - httpx==0.27.0
      - huggingface-hub==0.22.2
      - idna==3.6
      - imageio==2.34.0
      - importlib-resources==6.4.0
      - inflection==0.5.1
      - iniconfig==2.0.0
      - jinja2==3.1.3
      - jsonmerge==1.9.2
      - jsonschema==4.21.1
      - jsonschema-specifications==2023.12.1
      - kiwisolver==1.4.5
      - kornia==0.7.2
      - kornia-rs==0.1.3
      - lark==1.1.9
      - lazy-loader==0.4
      - lightning-utilities==0.11.2
      - llvmlite==0.42.0
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - matplotlib==3.8.4
      - mdurl==0.1.2
      - mixture-of-depth==1.1.2
      - mpmath==1.3.0
      - multidict==6.0.5
      - multiprocess==0.70.16
      - networkx==3.2.1
      - ninja==1.11.1.1
      - numba==0.59.1
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.19.3
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.1.105
      - omegaconf==2.3.0
      - open-clip-torch==2.24.0
      - opencv-python==4.9.0.80
      - orjson==3.10.0
      - packaging==24.0
      - pandas==2.2.1
      - peft==0.10.0
      - piexif==1.1.3
      - pillow==10.3.0
      - pluggy==1.4.0
      - protobuf==4.25.3
      - psutil==5.9.8
      - py-cpuinfo==9.0.0
      - pyarrow==15.0.2
      - pyarrow-hotfix==0.6
      - pydantic==2.6.4
      - pydantic-core==2.16.3
      - pydub==0.25.1
      - pygments==2.17.2
      - pynvml==11.5.0
      - pyparsing==3.1.2
      - pytest==8.1.1
      - python-dateutil==2.9.0.post0
      - python-multipart==0.0.9
      - pytorch-lightning==2.2.2
      - pytz==2024.1
      - pyyaml==6.0.1
      - referencing==0.34.0
      - regex==2023.12.25
      - requests==2.31.0
      - resize-right==0.0.2
      - rich==13.7.1
      - rpds-py==0.18.0
      - ruff==0.3.5
      - safetensors==0.4.2
      - scikit-image==0.23.1
      - scipy==1.13.0
      - segment-anything==1.0
      - semantic-version==2.10.0
      - sentencepiece==0.2.0
      - sentry-sdk==1.44.1
      - setproctitle==1.3.3
      - shellingham==1.5.4
      - shtab==1.7.1
      - simple-lama-inpainting==0.1.2
      - six==1.16.0
      - smmap==5.0.1
      - sniffio==1.3.1
      - sse-starlette==2.1.0
      - starlette==0.37.2
      - sympy==1.12
      - termcolor==2.4.0
      - tifffile==2024.2.12
      - timm==0.9.16
      - tokenizers==0.15.2
      - tomesd==0.1.3
      - tomli==2.0.1
      - tomlkit==0.12.0
      - toolz==0.12.1
      - torch==2.2.2
      - torchdiffeq==0.2.3
      - torchmetrics==1.3.2
      - torchsde==0.2.6
      - torchvision==0.17.2
      - tqdm==4.66.2
      - trampoline==0.1.2
      - transformers==4.39.3
      - triton==2.2.0
      - trl==0.8.1
      - typer==0.12.1
      - typing-extensions==4.10.0
      - tyro==0.8.0
      - tzdata==2024.1
      - urllib3==2.2.1
      - uvicorn==0.29.0
      - wandb==0.16.6
      - wcwidth==0.2.13
      - websockets==11.0.3
      - xxhash==3.4.1
      - yarl==1.9.4
prefix: /home/marco/miniconda3/envs/test_new
